import Header from '@/components/Header';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

export default function Import() {
  const [coffeehouseName, setCoffeeHouseName] = useState('');
  const [url, setUrl] = useState('');

  function submit_input() {
    console.log(coffeehouseName, url);
    fetch('/api/add', {
      method: 'POST',
      body: JSON.stringify({
        url: url,
        coffee_shop_name: coffeehouseName
      })
    });
    console.log('SUBMITTED');
  }

  return (
    <>
      <Head>
        <title>Import | Reviews Analyzer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className='container'>
          <h3 className='pt-3'>Input a URL</h3>
          <div className='input-group'>
            <input
              type='text'
              className='form-control my-3 py-2 my-1'
              placeholder='Enter a url (https://example.com)'
              aria-label='URL'
              value={url}
              onChange={(e) => setUrl(e.target.value)}
            />
          </div>
          <div className='input-group mb-3'>
            <input
              type='text'
              className='form-control py-2 my-1'
              placeholder='Coffeehouse Name'
              aria-label='Coffeehouse Name'
              value={coffeehouseName}
              onChange={(e) => setCoffeeHouseName(e.target.value)}
            />
          </div>
          <button className='btn btn-primary ms-1' onClick={submit_input}>
            Load
          </button>
        </div>
      </main>
    </>
  );
}
