import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div class="container">
      <h3 class="m-3">Reviews Sentiment Analysis</h3>
      <button class="btn btn-danger m-3">Previous</button>
      <button class="btn btn-primary m-3">Next</button>
      <div class="card m-4">
        <div class="card-body">
          <div class="alert alert-danger" role="alert">
            Has been chosen to be filtered
          </div>
          <small class="card-subtitle">Coffee Shop Name</small>
          <h2 class="card-title">Review Title</h2>
          <p>Review Text</p>

          <ul class="list-group">
            <ul class="list-group">
              <li class="list-group-item active">Important Keywords</li>
              {/* Loop over the keywords */}
              <li class="list-group-item" v-for="keyword in current_review.keywords">keywords</li>
            </ul>
          </ul>
        </div>
      </div>

    </div>
      </main>
    </>
  )
}
