import Head from 'next/head';
import Image from 'next/image';
import prisma from '../prisma-client';
import Header from '../components/Header';
// import { Inter } from '@next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <div className='container'>
          {props.reviews.map((review) => (
            <>
              <h1>{review.title}</h1>
              <p>{review.review}</p>
            </>
          ))}
          {/* <h3 className='m-3'>Reviews Sentiment Analysis</h3>
          <button className='btn btn-danger m-3'>Previous</button>
          <button className='btn btn-primary m-3'>Next</button>
          <div className='card m-4'>
            <div className='card-body'>
              <div className='alert alert-danger' role='alert'>
                Has been chosen to be filtered
              </div>
              <small className='card-subtitle'>Coffee Shop Name</small>
              <h2 className='card-title'>Review Title</h2>
              <p>Review Text</p>

              <ul className='list-group'>
                <ul className='list-group'>
                  <li className='list-group-item active'>Important Keywords</li>
                 // Loop over the keywords 
                  <li className='list-group-item'>keywords</li>
                </ul>
              </ul>
            </div>
          </div> */}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  let reviews = await prisma.review.findMany();

  return {
    props: {
      reviews: reviews
    }
  };
}
